Eso es lo que ha hecho nuestro ponente en la Comisión de Asuntos Económicos y Monetarios, el Sr. von Wogau.
Quiero felicitarlo, pese a que, lamentablemente, no está presente, por la forma completa y rigurosa como ha emprendido la preparación de su informe... ¡y también por haberme soportado como una espina clavada en su costado!
Antes ha dicho que el informe se ha aprobado con una mayoría importante, pero no con mi apoyo.
De modo que, aunque puedo no compartir sus conclusiones, creo que ha ilustrado en su informe muchas de las cuestiones que la Comisión debe abordar.
Hemos visto que el Tribunal Europeo no puede facilitarnos medidas provisionales en cierto litigio que tenemos con Francia en este momento, en el que contamos con el apoyo de la Comisión.
Quisiera preguntar a la Comisión si se ha emprendido un análisis de las consecuencias de ese cambio para las empresas: un análisis coste-beneficio del tipo que ahora está dándose mucho más en la política europea.
Se nos ha dicho que actualmente se está desperdiciando el tiempo de los ciudadanos y que, por tanto, los cambios podrían ser beneficiosos.
El sistema vigente favorece la transparencia, ofrece seguridad jurídica a las empresas, ha fomentado sin duda alguna la disciplina y ha tenido un efecto disuasorio a través de la notificación obligatoria.
Señor Presidente, me alegro mucho de que la Sra. Randzio-Plath haya mencionado el importantísimo marco de nuestro debate, porque hasta ahora ningún orador lo ha hecho.
Delegar en las autoridades nacionales está muy bien, pero quisiéramos subrayar lo que el Sr. von Wogau ha dicho en su informe sobre la necesidad de una supervisión periódica de las autoridades nacionales para velar por que no haya una reducción por la parte europea y quisiéramos pedir en particular al Comisario Monti que nos tranquilice, en el sentido de que habrá comprobaciones aleatorias al respecto.
Señor Presidente, en el reducido tiempo de que dispongo, quiero apoyar la labor realizada por todos los ponentes y compartir muchas de las cosas que se han dicho aquí, particularmente por mi compañero Jonckheer, criticando la excesiva agrupación de datos y la necesidad de transparencia y de balance socioeconómico de las ayudas.
Lo digo por si cupiera alguna duda por las críticas que hemos dirigido a la Comisión, en general, y al Sr. Monti, en particular, por su persecución de los incentivos a las empresas vascas y por el hecho de considerarlas como ayudas estatales.
La Unión Europea concedió acertadamente ayudas a la acería Grönitz de Brandenburgo, a pesar de que sus 5 000 puestos de trabajo ahora han quedado reducidos a sólo 700.
Quisiera recordar a Su Señoría que la Unión Europea ha aprobado las nuevas directrices en materia de ayuda regional para el período que se inicia en 2000.
La Comisión considera insatisfactoria la manera en que se ha llevado a cabo en la práctica la supervisión de dicha prohibición, con lo cual de entrada también podemos estar de acuerdo.
Los pedidos de la siderurgia y del sector naval -de este tema también hablamos hace poco- han disminuido drásticamente, con la subsiguiente pérdida de empleo.
Señor Presidente, el debate que hoy abordamos es extraordinariamente importante porque el principio de competencia ha sido probablemente la piedra angular del mercado interior.
En cuarto y último lugar -y ya se ha aludido a ello-, el orden jurídico internacional ha cambiado.
Y debemos vigilar por que se cumplan los estándares medioambientales, los estándares laborales, para evitar el dumping en este terreno, por que se respeten escrupulosamente los derechos de propiedad, que se revisen las ayudas estatales, que -como se ha dicho aquí- en muchos sectores distorsionan la competencia y destruyen empleo dentro de nuestra propia casa y, en definitiva, por que se apliquen condiciones similares que impidan que las ayudas, las distorsiones internas de otros países se trasladen al terreno internacional mediante trampas en definitiva.
A mi juicio, sería necesario crear un umbral por debajo del cual se deberían incorporar dos aspectos significativos que caracterizan nuestro tejido económico: las pequeñas y medianas empresas que representan el elemento de conjunción del universo económico europeo, y la protección social que Europa ha garantizado siempre a las capas económicas menos favorecidas.
Señor Presidente, intervenir en último lugar me da el privilegio, señor Comisario, de decirle que, mayoritariamente, esta Asamblea respalda su iniciativa y ha mostrado una total, y creo que muy justificada confianza, en la forma de conducir usted este barco.
En primer lugar, está la preocupación que algunos han expresado, en particular la Sra. Randzio-Plath, Presidenta de la Comisión de Asuntos Económicos, de que este nuevo sistema de excepción legal sea absolutamente compatible con el Tratado.
Pero no es menos cierto -y se ha repetido desde todos los sectores de esta Asamblea- que el tejido industrial europeo es un tejido de pequeña y mediana empresa, y que la Comisión, muchas veces, juega un papel de auctoritas, de legitimación, de legitimidad, de lo que es el mercado interior.
Y en este punto voy a dar mi opinión sobre algo que ha dicho el Sr. Karas.
¡Cuántas veces un abogado con dos empresas y un proyecto, ante una orientación de la Comisión dada ex ante, ha cambiado ese proyecto para que estuviera de acuerdo con las reglas de competencia!
Quisiera agrupar las consideraciones que se han hecho a lo largo del debate sobre el informe von Wogau en cuatro puntos que yo no considero como críticas a la Comisión, sino aportaciones fundamentales, dado que existen preocupaciones que es justo tener y que queremos superar juntos: la cuestión de la eficacia, la cuestión del riesgo de la renacionalización, la cuestión de la coherencia en la aplicación, la cuestión de la seguridad jurídica.
Señorías, el actual sistema de la notificación ya no permite alcanzar este objetivo, porque no garantiza la información de la Comisión sobre las restricciones más graves -recuerdo que en treinta y cinco años sólo nueve decisiones de prohibición han sido adoptadas después de una notificación y a falta de denuncia- no garantiza la transparencia y no aporta una verdadera seguridad jurídica a las empresas que, en la mayor parte de los casos, reciben una simple carta administrativa de archivo.
Figúrense si no nos hemos planteado este problema: nos lo hemos planteado y lo estamos estudiando con mucha atención, también gracias a las preocupaciones que ustedes han mostrado.
La reforma conducirá a un progresivo desarrollo -me permito subrayarlo porque me han llamado mucho la atención los términos que, por otra parte, comparto plenamente, utilizados por la presidenta Sra. Randzio-Plath- de la cultura europea de la competencia.
Después de todo, como muchas otras disposiciones del Tratado, los artículos 81.1 y 82 se aplican por parte de las autoridades y los jueces nacionales desde hace décadas, y no me parece que esto haya planteado grandes problemas.
Hemos recibido muchas observaciones y contribuciones excelentes que nos brindan el material para hacer un análisis del costo-beneficio para las empresas.
La han formulado la Sra. Thyssen, la Sra. Peijs y la Sra. Palacio Vallelersundi: la cuestión de las PYME.
Muchos oradores lo han subrayado.
Señor Rapkay, por lo que respecta a la dimensión internacional de la política de competencia, puedo confirmarle que la Comisión está dispuesta a facilitar al Parlamento un informe sobre este tema respecto al cual también la Sra. Randzio-Plath nos ha llamado la atención y en el ámbito del cual puedo decir que mantenemos relaciones bilaterales muy satisfactorias con las autoridades homólogas de los Estados Unidos, Canadá y Japón y que estamos trabajando para que, en el ámbito de la Organización Mundial del Comercio, nazca un verdadero volet competencia.
Continuaremos, sobre todo con la Comisión de Asuntos Económicos y Monetarios, pero más en general con el Parlamento, ese diálogo interinstitucional que se ha establecido.
Y quisiera añadir que la competencia ha tenido y continuará teniendo un valor civil y no sólo económico en la construcción europea.
Hasta ahora, al cabo de cinco años, sólo cuatro de ellos lo han hecho.
Ante este punto muerto en el que nos encontramos y que amenaza con minar la credibilidad de la Unión, el Parlamento ha tomado la iniciativa de solicitar la creación de un Ministerio público europeo.
Creo que éste ha sido un informe en el que la cooperación entre comisiones ha funcionado muy bien, y el resultado, que nos llega hoy, es un informe sobrio y sereno en una materia especialmente delicada.
Y a la vez, es una cuestión especialmente delicada porque se trata de la protección de los intereses financieros de la Comunidad, como muy bien ha dicho la Sra. Theato.
Pero cuidado, como dicen los franceses, "ne jettons pas le bébé avec l'eau du bain" , es decir, en la protección de los intereses financieros de la Comunidad han de respetarse, por una parte -y lo ha dicho la Sra. Theato- las competencias de los Estados nacionales, pero también otras cosas que afectan a los ciudadanos, que afectan a las garantías esenciales.
Sólo tengo la sensación de que en el fondo ella quería haber ido aún un poco más lejos en este estadio.
Señor Presidente, estamos básicamente a favor de la resolución que se nos ha presentado, aunque pensamos que ésta no puede sino ser una invitación del Parlamento al Consejo para que, a través de una modificación de los Tratados, se garantice una protección penal eficaz de los intereses financieros de la Unión.
La institución de un Fiscal europeo y el establecimiento de figuras delictivas comunes a todos los Estados de la Unión es, sin duda, una buena idea, sin embargo, considero imposible pensar en llevarla a la práctica sin antes haber creado un ordenamiento judicial de la Unión.
De hecho, es impensable que se puedan establecer normas jurídicas sustantivas y procesales para un solo ámbito como el de la protección de los intereses financieros, sin haber creado antes un ordenamiento judicial europeo.
No obstante, estoy de acuerdo con el Sr. ponente: es absolutamente inaceptable que la mayoría de países miembros no lo haya ratificado todavía.
No hay ninguna legislación europea vigente en materia de lucha contra el fraude, porque los Estados miembros, ya se ha dicho, no ratifican los tratados.
Quisiera apoyar lo que la Sra. Morgan ha dicho sobre esta cuestión.
Yo creo que, ante las dificultades jurídicas que plantea esta cuestión -y es evidente que la Unión Europea sólo dispone de una vía muy estrecha para conseguir que dichos delitos sean perseguibles judicialmente como delitos europeos- se ha perdido el rumbo jurídico.
En ellas ya no se habla de un fiscal europeo sino que, por razones jurídicas, éste se ha convertido ahora en una autoridad europea independiente, un organismo lo ha llamado antes la Sra. Theato.
Aun así, es imprescindible -y por esto vamos a votar a favor del punto 1 excluida esta recomendación- es que el Parlamento transmita a la Comisión y al Consejo una señal clara de nuestra voluntad de que se ponga fin, mediante un acto normativo claro, a las situaciones que han acabado arraigando.
La verdad es que la frustración aumenta cuando se comprueba la fragilidad del Convenio (y los protocolos relativos a dicha protección), que, cinco años después de su firma, aún no ha sido ratificado ni ha entrado en vigor.
Yo quiero manifestar a la ponente el reconocimiento de la Comisión por la dedicación con que ha vuelto a examinar el tema francamente difícil de los fundamentos jurídicos que es posible crear y las modificaciones institucionales que se pueden introducir para intensificar la lucha contra el fraude en detrimento de los intereses de la Unión Europea.
En realidad, el presupuesto europeo se alimenta del IVA y de la retención sobre el PIB, sobre todo desde que el abandono de la preferencia comunitaria y la multiplicación de las zonas de libre comercio han hecho desaparecer los derechos arancelarios y la exacción reguladora agrícola común, ya amputados por los SPG.
Lo vemos perfectamente en el reglamento que nos ha sido presentado.
Las empresas de transporte de mercancías peligrosas y aquéllas que realizan las operaciones de carga o descarga relativas a este transporte han visto cómo se les imponía, acertadamente, el cumplimiento de normas en materia de prevención de riesgos, ya se trate del transporte por carretera, por ferrocarril o por vía navegable.
Para facilitar la realización de este objetivo, la Directiva 96/35/CE ha previsto el nombramiento de consejeros de seguridad para el transporte de mercancías peligrosas, que hayan recibido una formación profesional adecuada.
No obstante, ha presentado varias enmiendas, la mayor parte de las cuales se han mantenido en la posición común del Consejo, en particular, en lo que respecta a la necesidad de elaborar un cuestionario y declaraciones relativas a la autorización de determinados documentos en el marco "de las especificaciones de las modalidades del examen propuestas por el organismo examinador" .
Es exactamente lo que ha ocurrido en el caso del transporte de este tipo de mercancías por ferrocarril, excepto esta diferencia: se había fijado un plazo.
Señor Presidente, en relación con el informe Schroedter, sé -y he pedido al Sr. Barnier que me lo confirme- que las normas sobre la adicionalidad en el caso de los Fondos estructurales sólo se aplican en el nivel de los Estados miembros y no de forma transitiva y transparente dentro de los Estados miembros a favor de regiones autónomas como Gales y Escocia.
Quiero que quede claro que, aunque he votado a favor del informe, abrigo esta importante reserva.
Es el motivo por el que apoyaré este informe, al tiempo que lamento que, por motivos de calendario, el Parlamento Europeo sólo haya sido consultado de forma muy tardía sobre las orientaciones que se supone deben ayudar a los Estados miembros, a las regiones y a las colectividades locales en la programación de los objetivos 1, 2, y 3.
En teoría, podríamos incluso responder positivamente a la petición de la Comisión de crear un centro de gestión para la promoción estructural en los Estados miembros, encargado de coordinar la actuación y la gestión de las ayudas estructurales in situ, con tal que dicho centro no resulte ser un instrumento centralizador de carácter supranacional y garantice una efectiva atención a aquellas regiones -vuelvo a repetirlo- que, por una serie de factores negativos convergentes, no han alcanzado todavía niveles correctos de utilización de los Fondos estructurales, por lo que la sustitución del objetivo geográfico por las políticas sectoriales, en la práctica podría resultar una intervención negativa.
Así las cosas, podríamos decir que una vez más se ha perdido la ocasión de potenciar realmente el desarrollo urbano sostenible, mediante una contención del creciente fenómeno del traslado masivo de la población hacia los centros industrializados y de la consiguiente degradación del entorno.
No ha sido valorada adecuadamente la importancia del instrumento de la subvención global que podría revelarse extraordinariamente útil de cara al reequilibrio entre zonas urbanas y rurales confiriendo, por otra parte, una justa dignidad a las entidades locales que, en su autonomía, podrían determinar condiciones de desarrollo territorial en plazos más cortos y contribuir de hecho a los esfuerzos de reforma de los Fondos estructurales y a los objetivos de eficacia, concentración y agilización administrativa.
En unos momentos en que los Estados miembros se ven obligados a seguir una dieta de adelgazamiento presupuestario para cumplir los criterios de convergencia, dieta que, por otra parte, se han impuesto de motu propio, los federalistas dan muestras de una glotonería pecuniaria muy sorprendente.
Esto resulta especialmente claro en Francia: la región Champagne-Ardennes, que tengo el honor de representar, ha visto su PIB pasar del 105 al 94% de la media comunitaria, el de Pays-de-Loire se ha debilitado desde el 95 hasta el 91%, el de Auvergne, del 89 al 83%.
Por ello, puede parecer extraño que se haya sacrificado el objetivo 2, destinado a las regiones industriales y rurales en vías de reestructuración económica, a raíz de la reforma de los Fondos estructurales y en beneficio de los objetivos 1 y 3: su dotación para el período 1999-2006 será de 22.500 millones de ecus, una suma más o menos parecida a la del período 1994-1999.
El informe de la Comisión de Asuntos Económicos y Monetarios es insuficiente desde este punto de vista, motivo por el que me he abstenido.
Por otro lado, como recuerda el ponente, muchas veces, en nombre de la política de competencia, se han substituido monopolios públicos por monopolios privados con las privatizaciones de importantes sectores y empresas públicos, como ha ocurrido en Portugal, con consecuencias negativas para el país y para los trabajadores.
En efecto, tras haber tomado nota del atasco de sus servicios a causa de las notificaciones previas de acuerdos de empresas susceptibles de torcer el comercio y por temor a que su número siga creciendo con la llegada de nuevos países miembros, la Comisión propone la supresión del régimen de autorización previa de estos acuerdos y una aplicación más descentralizada de las normas de competencia a nivel de los Estados miembros.
. (FR) Al votar en contra de este informe, nos convertimos en portavoces de todas aquellas y de todos aquellos que han expresado su rechazo en Seattle y en toda Europa a un mundo reducido a la estricta lógica mercantil.
Al igual que el ponente, acojo con satisfacción el informe de la Comisión, pero he deplorado que este informe no cubra todos los aspectos de las ayudas.
Por todas estas razones, he votado a favor del informe Langen y espero que la Comisión atienda ahora a nuestras peticiones y a nuestras exigencias.
Sin hubiéramos contado con semejantes disposiciones, repito, la catástrofe sin duda no se habría producido.
Por eso creemos que hay que revisar los textos aplicables y, en particular, el protocolo de 1992, que ha exonerado a los fletadores, en este caso al petrolero fletador, de toda responsabilidad.
Por otra parte, como usted ha dicho, debemos sobre todo reforzar los controles: los controles del Estado del pabellón y aquéllos de las sociedades de clasificación.
Usted nos ha dicho que la sociedad RINA es un registro de clasificación italiano reconocido por la Comisión.
¿Cuáles son las consecuencias que ha sacado o que piensa sacar la Comisión de esta situación?
Podría recitar de un tirón la lista de desastres que han afectado a esa industria en los 10 años que llevo en este Parlamento, pero sólo dispongo de tres minutos.
Si bien reconozco que se han logrado algunos avances en sectores como los de control por el Estado del puerto y normas sobre tripulación mínima, seguimos afrontando lo que nuestro difunto colega Ken Stewart llamaba "buques de la vergüenza que entran en nuestras aguas de la Unión Europea y salen de ellas: cubos oxidados y con tripulación deficiente".
Mi Grupo expresa su condolencia a la población de Bretaña que ha visto su zona saqueada por ese desastre, como también se lo expresó en ocasiones anteriores a la población del Gales occidental y a la de las islas Shetland.
Hay quien dice que es el peor accidente que haya sucedido jamás a la vida de las aves de esta parte de Europa.
La Sociedad Real para la Protección de las Aves cree que nada menos que 400.000 aves, tal vez araos principalmente, pueden haber muerto.
Las fotografías que muchos de nosotros hemos visto de aves empapadas de petróleo y que veterinarios oficiales estaban sacrificando eran a un tiempo penosas y trágicas.
Estoy de acuerdo con todas las palabras que la Comisaria ha pronunciado en sus observaciones, pero la cuestión es: ¿cuánto se tardará en lograr que se presenten las medidas encaminadas a abordar ese problema como ella propone?
Como político, debe recordar a sus funcionarios lo difícil que sería que hubiera de volver a este Parlamento dentro de un año, si se produjera un accidente similar, igualmente devastador, en caso de que algunas de las medidas que ha propuesto hoy siguieran, sencillamente, siendo bonitas palabras y no hubiese tenido la oportunidad de ponerlas en práctica.
Señor Presidente, señora Comisaria, le he traído un pequeño regalo: una torta de aceite pesado que me ha enviado una habitante de la isla de Noirmoutier, que me escribe lo siguiente: "con cada marea, la playa se cubre de aceite pesado que escapa del Erika.
Ahora bien, al escucharla, señora Comisaria, nos sentimos algo frustrados, porque aquellos que ya se han ocupado de estas cuestiones saben que la Comisión y el Parlamento habían preparado, creo que en 1992, un texto muy interesante que ya incluía todas las propuestas contenidas en la resolución que hoy presenta la Comisión de Transportes.
Expresar su solidaridad es algo que muchos voluntarios de Francia y de diferentes países europeos han hecho al echar una mano a las víctimas sobre el terreno.
Lo que ahora esperan las poblaciones siniestradas, quienes lo han perdido todo, en particular entre los profesionales del mar y del turismo, aquellos cuya actividad está comprometida para varios años, es no sólo que los contaminadores reparen los daños que han causado, sino también que se haga todo lo necesario para que su desgracia actual sirva en el futuro a los demás para impedir la repetición de semejantes delitos.
Se deben tratar esos asuntos -resulta más que evidente- en el nivel mundial, pero las normas internacionales actuales de la OMI son muy insuficientes y mucho más laxistas y ni nuestros países ni la Comunidad han procurado con tesón volverlas más rigurosas, pese a las catástrofes recientes.
De no conseguirse un marco reglamentario comunitario suficientemente claro, estricto y riguroso, se debería autorizar a los Estados miembros que lo deseen, por su parte, a establecerlo para proteger a su población y su territorio, del mismo modo que los Estados Unidos han sabido, por su parte, aprovechar las enseñanzas de la catástrofe del Exxon Valdez exigiendo el doble casco y vedando sus aguas a todos los buques de más de veinte años.
Procuremos, señor Presidente, señora Comisaria, aprovechar esta vez la enseñanza de verdad, aun cuando haya decaído la emoción parlamentaria y en los medios de comunicación.
